services:
  kofem-web:
    image: ghcr.io/mkofler96/kofem-web:latest
    container_name: kofem-web
    restart: always
    expose:
      - "10000"
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
    name: dashboard_mybasil-network
