#!/usr/bin/env -S bun run
/**
 * Generate a PDF mesh capabilities report from Playwright screenshots.
 * Run after: bun run test:mesh-report
 * Usage:  bun scripts/generate-mesh-report.ts
 */
import { jsPDF } from 'jspdf'
import fs from 'fs'
import path from 'path'

const SHOT_DIR = path.join(import.meta.dir, '..', 'screenshots', 'report')
const OUT_FILE = path.join(import.meta.dir, '..', 'screenshots', 'mesh-report.pdf')

interface GeomEntry {
  file: string
  label: string
  desc: string
}

const GEOMETRIES: GeomEntry[] = [
  { file: 'box',           label: 'Simple Box',         desc: '80 × 60 × 40 mm — 6 planar faces' },
  { file: 'cylinder',      label: 'Cylinder',           desc: 'R = 25 mm, H = 80 mm — cylindrical surface + 2 caps' },
  { file: 'l_bracket',     label: 'L-Bracket',          desc: '80 × 80 × 20 mm — 8 planar faces, re-entrant corner' },
  { file: 'new_bracket_2', label: 'Complex Bracket',    desc: 'Imported STEP — curved faces, blends, multiple features' },
]

function pngToDataUrl(filePath: string): string | null {
  if (!fs.existsSync(filePath)) return null
  const buf = fs.readFileSync(filePath)
  return `data:image/png;base64,${buf.toString('base64')}`
}

function run() {
  // A4 landscape: 297 × 210 mm
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const PW = 297, PH = 210
  const M = 12                 // page margin
  const COL_LABEL = 36         // width of label column
  const GAP = 6                // gap between image columns
  const IMG_W = (PW - 2*M - COL_LABEL - GAP) / 2   // ~114 mm each
  const ROW_H = (PH - 2*M - 24) / GEOMETRIES.length // ~40 mm each row

  // ── Cover / header ──────────────────────────────────────────────────────────
  doc.setFillColor(18, 18, 38); doc.rect(0, 0, PW, PH, 'F')
  doc.setFillColor(59, 91, 219); doc.rect(0, 0, PW, 2, 'F')

  doc.setFont('helvetica', 'bold'); doc.setFontSize(20)
  doc.setTextColor(224, 224, 240)
  doc.text('KoFEM — Meshing Capabilities', M, M + 8)

  doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
  doc.setTextColor(136, 136, 170)
  doc.text(
    `Surface tessellation test suite — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    M, M + 14,
  )

  // Column headers
  const tableTop = M + 22
  const imgColL = M + COL_LABEL
  const imgColR = imgColL + IMG_W + GAP

  doc.setFont('helvetica', 'bold'); doc.setFontSize(8)
  doc.setTextColor(100, 120, 200)
  doc.text('Geometry', M + 2, tableTop - 2)
  doc.text('Rendered surface', imgColL + IMG_W / 2, tableTop - 2, { align: 'center' })
  doc.text('Surface mesh (wireframe)', imgColR + IMG_W / 2, tableTop - 2, { align: 'center' })

  doc.setDrawColor(50, 50, 90); doc.setLineWidth(0.3)
  doc.line(M, tableTop, PW - M, tableTop)

  // ── Rows ─────────────────────────────────────────────────────────────────────
  for (let i = 0; i < GEOMETRIES.length; i++) {
    const g = GEOMETRIES[i]
    const rowY = tableTop + i * ROW_H
    const imgY = rowY + 2
    const imgH = ROW_H - 4

    // Row stripe
    if (i % 2 === 0) {
      doc.setFillColor(22, 22, 44)
      doc.rect(M, rowY, PW - 2*M, ROW_H, 'F')
    }

    // Label column
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5)
    doc.setTextColor(200, 210, 240)
    doc.text(g.label, M + 2, rowY + 7)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(110, 120, 160)
    const descLines = doc.splitTextToSize(g.desc, COL_LABEL - 4)
    doc.text(descLines, M + 2, rowY + 13)

    // Geometry (solid) image
    const geoPath = path.join(SHOT_DIR, `${g.file}-geometry.png`)
    const geoUrl = pngToDataUrl(geoPath)
    if (geoUrl) {
      doc.addImage(geoUrl, 'PNG', imgColL, imgY, IMG_W, imgH)
    } else {
      doc.setFillColor(30, 30, 55); doc.rect(imgColL, imgY, IMG_W, imgH, 'F')
      doc.setFontSize(7); doc.setTextColor(80, 80, 110)
      doc.text('screenshot missing', imgColL + IMG_W/2, imgY + imgH/2, { align: 'center' })
    }

    // Mesh (wireframe) image
    const meshPath = path.join(SHOT_DIR, `${g.file}-mesh.png`)
    const meshUrl = pngToDataUrl(meshPath)
    if (meshUrl) {
      doc.addImage(meshUrl, 'PNG', imgColR, imgY, IMG_W, imgH)
    } else {
      doc.setFillColor(30, 30, 55); doc.rect(imgColR, imgY, IMG_W, imgH, 'F')
      doc.setFontSize(7); doc.setTextColor(80, 80, 110)
      doc.text('screenshot missing', imgColR + IMG_W/2, imgY + imgH/2, { align: 'center' })
    }

    // Row separator
    doc.setDrawColor(35, 35, 65); doc.setLineWidth(0.2)
    doc.line(M, rowY + ROW_H, PW - M, rowY + ROW_H)
  }

  // Footer
  doc.setFontSize(7); doc.setTextColor(60, 60, 90)
  doc.text('Generated by KoFEM — browser-first finite element analysis', PW/2, PH - 5, { align: 'center' })

  // Write file
  const arrayBuf = doc.output('arraybuffer')
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, Buffer.from(arrayBuf))
  console.log(`Report written to ${OUT_FILE}`)
}

run()
