// Type declarations for the kofem_wasm WebAssembly module.
// The actual .js/.wasm files are generated by scripts/build-wasm.sh and are gitignored.

/** Tessellated STEP surface returned as flat typed arrays (binary, no JSON text).
 *  `vertices` is xyz interleaved (length 3·nVerts); `triangles` is three 0-based
 *  vertex indices per triangle (length 3·nTris). */
export interface StepTessellation {
  vertices: Float32Array
  triangles: Uint32Array
}

/** Runtime interface of the initialised Emscripten/Embind module. */
export interface KofemModule {
  /** Load a STEP or IGES file and tessellate it for display.
   *  @param cad_bytes Raw STEP/IGES file bytes.
   *  @param opts_json JSON `{ deflection_relative?, linear_deflection?, angular_deflection?, format?: "step" | "iges" }`.
   *                   `format` selects the reader (defaults to "step").
   */
  tessellate_step(cad_bytes: Uint8Array, opts_json: string): StepTessellation
  tessellate_for_meshing(opts_json: string): string
  generate_volume_mesh(surface_json: string, opts_json: string): string
  /** Generate a FEM surface mesh + volume mesh directly from the stored STEP geometry
   *  using Netgen's native OCC integration.  Must call tessellate_step first.
   *  @param opts_json JSON `{ max_element_size, min_element_size, grading, second_order, elementsperedge, elementspercurve, optsteps_2d, optsteps_3d }`
   *  @returns JSON `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][] }`
   */
  generate_fem_mesh(opts_json: string): string
  /** Release the OCCT shape + STEP byte cache from WASM heap.
   *  Call this after meshing is complete and before solving to free ~10–30 MB
   *  of WASM memory that is no longer needed.
   */
  free_geometry_cache(): void
  solve_linear_elastic(mesh_json: string, mat_json: string, bcs_json: string, order: number): string
}

export interface ModuleOverrides {
  print?: (text: string) => void
  printErr?: (text: string) => void
  wasmBinary?: ArrayBuffer
}

/** Initialise the WASM module and return it. Must be awaited before using any function. */
export default function init(overrides?: ModuleOverrides): Promise<KofemModule>
