// Type declarations for the kofem_wasm WebAssembly module.
// The actual .js/.wasm files are generated by scripts/build-wasm.sh and are gitignored.

/** Runtime interface of the initialised Emscripten/Embind module. */
export interface KofemModule {
  tessellate_step(step_bytes: Uint8Array, opts_json: string): string
  tessellate_for_meshing(opts_json: string): string
  generate_volume_mesh(surface_json: string, opts_json: string): string
  solve_linear_elastic(mesh_json: string, mat_json: string, bcs_json: string, order: number): string
  step_to_fem_result(
    step_bytes: Uint8Array,
    tess_opts_json: string,
    mesh_opts_json: string,
    mat_json: string,
    bcs_json: string,
    order: number
  ): string
}

export interface ModuleOverrides {
  print?: (text: string) => void
  printErr?: (text: string) => void
  wasmBinary?: ArrayBuffer
}

/** Initialise the WASM module and return it. Must be awaited before using any function. */
export default function init(overrides?: ModuleOverrides): Promise<KofemModule>

/** Load a STEP file and tessellate it into a closed surface triangle mesh.
 *  @param step_bytes Raw STEP file bytes.
 *  @param opts_json  JSON-serialised `{ linear_deflection: number, angular_deflection: number }`.
 *  @returns JSON-serialised `{ vertices: [number,number,number][], triangles: [number,number,number][] }`.
 */
export function tessellate_step(step_bytes: Uint8Array, opts_json: string): string

/** Generate a quality tetrahedral volume mesh from a closed surface mesh.
 *  @param surface_json JSON-serialised `{ vertices: [number,number,number][], triangles: [number,number,number][] }`.
 *  @param opts_json    JSON-serialised `{ max_element_size: number, min_element_size: number, grading: number, second_order: boolean }`.
 *  @returns JSON-serialised `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][] }`.
 */
export function generate_volume_mesh(surface_json: string, opts_json: string): string

/** Run a linear-elastic FEM solve using MFEM.
 *  @param mesh_json JSON-serialised `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][], hexahedra: [number,number,number,number,number,number,number,number][] }`.
 *  @param mat_json  JSON-serialised `{ young_modulus: number, poisson_ratio: number, density: number }`.
 *  @param bcs_json  JSON-serialised `{ fixed_vertices: number[], point_loads: { vertex: number, force: [number,number,number] }[] }`.
 *  @param order     FE polynomial order (1 = linear, 2 = quadratic).
 *  @returns JSON-serialised `{ displacements: number[], von_mises: number[] }`.
 */
export function solve_linear_elastic(
  mesh_json: string,
  mat_json: string,
  bcs_json: string,
  order: number
): string

/** Full pipeline: STEP bytes → tessellate → volume mesh → FEM solve. */
export function step_to_fem_result(
  step_bytes: Uint8Array,
  tess_opts_json: string,
  mesh_opts_json: string,
  mat_json: string,
  bcs_json: string,
  order: number
): string
