// Type declarations for the kofem_wasm WebAssembly module.
// The actual .js/.wasm files are generated by scripts/build-wasm.sh and are gitignored.

/** Runtime interface of the initialised Emscripten/Embind module. */
export interface KofemModule {
  /** Load a STEP or IGES file and tessellate it for display.
   *  @param cad_bytes Raw STEP/IGES file bytes.
   *  @param opts_json JSON `{ linear_deflection, angular_deflection, format?: "step" | "iges" }`.
   *                   `format` defaults to "step".
   */
  tessellate_step(cad_bytes: Uint8Array, opts_json: string): string
  tessellate_for_meshing(opts_json: string): string
  generate_volume_mesh(surface_json: string, opts_json: string): string
  /** Generate a FEM surface mesh + volume mesh directly from the stored STEP geometry
   *  using Netgen's native OCC integration.  Must call tessellate_step first.
   *  @param opts_json JSON `{ max_element_size, min_element_size, grading, second_order, elementsperedge, elementspercurve, optsteps_2d, optsteps_3d }`
   *  @returns JSON `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][] }`
   */
  generate_fem_mesh(opts_json: string): string
  /** Release the OCCT shape + STEP byte cache from WASM heap.
   *  Call this after meshing is complete and before solving to free ~10–30 MB
   *  of WASM memory that is no longer needed.
   */
  free_geometry_cache(): void
  solve_linear_elastic(mesh_json: string, mat_json: string, bcs_json: string, order: number): string
}

export interface ModuleOverrides {
  print?: (text: string) => void
  printErr?: (text: string) => void
  wasmBinary?: ArrayBuffer
}

/** Initialise the WASM module and return it. Must be awaited before using any function. */
export default function init(overrides?: ModuleOverrides): Promise<KofemModule>

/** Load a STEP or IGES file and tessellate it into a closed surface triangle mesh.
 *  @param cad_bytes Raw STEP/IGES file bytes.
 *  @param opts_json JSON-serialised `{ linear_deflection: number, angular_deflection: number, format?: "step" | "iges" }`.
 *  @returns JSON-serialised `{ vertices: [number,number,number][], triangles: [number,number,number][] }`.
 */
export function tessellate_step(cad_bytes: Uint8Array, opts_json: string): string

/** Generate a quality tetrahedral volume mesh from a closed surface mesh.
 *  @param surface_json JSON-serialised `{ vertices: [number,number,number][], triangles: [number,number,number][] }`.
 *  @param opts_json    JSON-serialised `{ max_element_size: number, min_element_size: number, grading: number, second_order: boolean }`.
 *  @returns JSON-serialised `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][] }`.
 */
export function generate_volume_mesh(surface_json: string, opts_json: string): string

/** Run a linear-elastic FEM solve using MFEM.
 *  @param mesh_json JSON-serialised `{ vertices: [number,number,number][], tetrahedra: [number,number,number,number][], hexahedra: [number,number,number,number,number,number,number,number][] }`.
 *  @param mat_json  JSON-serialised `{ young_modulus: number, poisson_ratio: number, density: number }`.
 *  @param bcs_json  JSON-serialised `{ fixed_vertices: number[], point_loads: { vertex: number, force: [number,number,number] }[] }`.
 *  @param order     FE polynomial order (1 = linear, 2 = quadratic).
 *  @returns JSON-serialised `{ displacements: number[], von_mises: number[] }`.
 */
export function solve_linear_elastic(
  mesh_json: string,
  mat_json: string,
  bcs_json: string,
  order: number
): string
